name: nginxadminui

services:
   main-server:
      container_name: nginxadminui
      image: joyte/nginxadminui:latest
      volumes:
         - "./sites_available:/etc/nginx/sites-available"
         - "./html:/var/www/html"
      restart: always
      ports:
         - "80:80"
         - "81:81"
         - "443:443"
      depends_on:
         - php-fpm
         - db

   php-fpm:
      container_name: php-fpm
      image: php:fpm
      volumes:
         - "./html:/var/www/html"
      restart: always

   db:
      image: mariadb:latest
      container_name: mariadb
      environment:
         # !! Leave the environment variables as is
         MYSQL_ROOT_PASSWORD: 6YFHqehrHD6X3GCM
         MYSQL_DATABASE: main_db
         MYSQL_USER: nginxadminui
         MYSQL_PASSWORD: cuzw2pKMsEjmeuLb
      volumes:
         - ./db_data:/var/lib/mysql
      restart: always
